apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa-app
  labels:
    role: hpa_role
spec:
  replicas: 3
  selector:
    matchLabels:
      role: hpa_role
  template:
    metadata:
      labels:
        role: hpa_role
    spec:
      containers:
      - name: hpa-app
        image: k8s.gcr.io/hpa-example
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "200m"
