apiVersion: v1
kind: Pod
metadata:
  name: init-container
spec:
  initContainers:
  - name: sleepy
    image: alpine
    command: [ "/bin/sleep" ]
    args: [ "10" ]
  containers:
  - name: web
    image: nginx
